#!/bin/sh
#
# @name Fully Actuated Hexarotor x geometry
#
# @type Hexarotor x
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

# MAV_TYPE_HEXAROTOR 13
param set-default MAV_TYPE 13

param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.1455
param set-default CA_ROTOR0_PY 0.084
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR0_AX -0.1710
param set-default CA_ROTOR0_AY 0.2962
param set-default CA_ROTOR0_AZ -0.9397

param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0.168
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR1_AX 0.3420
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -0.9397

param set-default CA_ROTOR2_PX -0.1455
param set-default CA_ROTOR2_PY 0.084
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR2_AX -0.1710
param set-default CA_ROTOR2_AY -0.2962
param set-default CA_ROTOR2_AZ -0.9397

param set-default CA_ROTOR3_PX -0.1455
param set-default CA_ROTOR3_PY -0.084
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_AX -0.1710
param set-default CA_ROTOR3_AY 0.2962
param set-default CA_ROTOR3_AZ -0.9397

param set-default CA_ROTOR4_PX 0
param set-default CA_ROTOR4_PY -0.168
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR4_AX 0.3420
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ -0.9397

param set-default CA_ROTOR5_PX 0.1455
param set-default CA_ROTOR5_PY -0.084
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR5_AX -0.1710
param set-default CA_ROTOR5_AY -0.2962
param set-default CA_ROTOR5_AZ -0.9397

param set-default PWM_MAIN_FUNC1 106
param set-default PWM_MAIN_FUNC2 105
param set-default PWM_MAIN_FUNC3 104
param set-default PWM_MAIN_FUNC4 103
param set-default PWM_MAIN_FUNC5 102
param set-default PWM_MAIN_FUNC6 101
